apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
 name: default
spec:
 mtls:
   enabledBackend: ca-1
   backends:
     - name: ca-1
       type: builtin
       mode: PERMISSIVE # supported values: STRICT, PERMISSIVE
       dpCert:
         rotation:
           expiration: 1y
       conf:
         caCert:
           RSAbits: 2048
           expiration: 10y
