apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"prometheus","component":"server"},"name":"prometheus-server","namespace":"mesh-observability"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"8Gi"}}}}
    creationTimestamp: "2024-08-16T17:21:23Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: prometheus
      component: server
    name: prometheus-server
    namespace: mesh-observability
    resourceVersion: "9941"
    uid: 29bbc6b9-55a2-4fbc-804a-54e953362e11
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    volumeMode: Filesystem
  status:
    phase: Pending
kind: List
metadata:
  resourceVersion: ""
