apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"redis","namespace":"kuma-demo"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"redis"}},"template":{"metadata":{"labels":{"app":"redis"}},"spec":{"containers":[{"image":"redis","lifecycle":{"postStart":{"exec":{"command":["/usr/local/bin/redis-cli","set","zone","local"]}},"preStop":{"exec":{"command":["/bin/sleep","30"]}}},"name":"redis","ports":[{"containerPort":6379,"name":"tcp"}]}]}}}}
  creationTimestamp: "2024-08-16T16:24:54Z"
  generation: 1
  name: redis
  namespace: kuma-demo
  resourceVersion: "2002"
  uid: 1c7a8800-f892-48f9-9688-e5ef20f11095
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
              - /usr/local/bin/redis-cli
              - set
              - zone
              - global
          preStop:
            exec:
              command:
              - /bin/sleep
              - "30"
        name: redis
        ports:
        - containerPort: 6379
          name: tcp
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-08-16T16:25:41Z"
    lastUpdateTime: "2024-08-16T16:25:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-08-16T16:24:54Z"
    lastUpdateTime: "2024-08-16T16:25:41Z"
    message: ReplicaSet "redis-5484ddcc64" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
